"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ku_as45vs5isd^px=t#m8g#^*x7f=w#gw-xb^t@^-pom)r^t6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '.kavia.ai',
    'localhost',
    '127.0.0.1',
    'testserver',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'api'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os

import dj_database_url

def get_db_setting(var, fallback):
    # Lookup DB_* first, fallback to legacy POSTGRES_*, then use hardcoded default
    return os.environ.get(var, os.environ.get('POSTGRES_' + var[3:], fallback))

DATABASES = {}

DATABASE_URL = os.getenv("DATABASE_URL")

# Prefer psycopg (psycopg3) if possible, fallback to psycopg2 otherwise
# dj_database_url will produce psycopg2 for ENGINE, so we patch it if needed
def _prefer_psycopg(db_cfg):
    if db_cfg.get("ENGINE", "").startswith("django.db.backends.postgresql"):
        # Prefer psycopg if installed
        try:
            import psycopg  # noqa: F401
            db_cfg["ENGINE"] = "django.db.backends.postgresql"
        except ImportError:
            db_cfg["ENGINE"] = "django.db.backends.postgresql_psycopg2"
    return db_cfg

if DATABASE_URL:
    db_cfg = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    db_cfg = _prefer_psycopg(db_cfg)
    # Ensure sane NAME fallback if not set in URL
    db_cfg.setdefault("NAME", "notes_db")
    db_cfg.setdefault("USER", "postgres")
    db_cfg.setdefault("PASSWORD", "postgres")
    db_cfg.setdefault("HOST", "localhost")
    db_cfg.setdefault("PORT", "5432")
    DATABASES['default'] = db_cfg
else:
    # Set sensible defaults for running with a typical local PostgreSQL service
    db_cfg = {
        'ENGINE': 'django.db.backends.postgresql',
        # These defaults are compatible with the Kavia-provided Postgres container, and work for local development.
        'NAME': get_db_setting('DB_NAME', 'notes_db'),  # Use 'notes_db' if not set
        'USER': get_db_setting('DB_USER', 'postgres'),
        'PASSWORD': get_db_setting('DB_PASSWORD', 'postgres'),
        'HOST': get_db_setting('DB_HOST', 'localhost'),
        'PORT': get_db_setting('DB_PORT', '5432'),
    }
    db_cfg = _prefer_psycopg(db_cfg)
    DATABASES['default'] = db_cfg


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
X_FRAME_OPTIONS = 'ALLOWALL'
