"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0ku_as45vs5isd^px=t#m8g#^*x7f=w#gw-xb^t@^-pom)r^t6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '.kavia.ai',
    'localhost',
    '127.0.0.1',
    'testserver',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'api'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --- DATABASE CONFIGURATION ---

# CRITICAL:
# - This section must NEVER import psycopg or socket or perform any direct/indirect host or net resolution.
# - No database connection, DNS check, or network activity occurs at settings import time.
# - All configuration is based purely on environment variables, with safe Docker-style fallbacks.
# - dj-database-url is only used if DATABASE_URL is present, and performs zero connection or host validation at parse time.

def _env(var, fallback):
    v = os.getenv(var)
    if v is not None:
        return v
    # Accept legacy POSTGRES_* fallback
    legacy_v = os.getenv('POSTGRES_' + var[3:]) if var.startswith("DB_") else None
    if legacy_v is not None:
        return legacy_v
    return fallback

DB_DEFAULTS = {
    "DB_NAME": "notes_db",
    "DB_USER": "postgres",
    "DB_PASSWORD": "postgres",
    "DB_HOST": "database",      # Critical: Never default to localhost!
    "DB_PORT": "5001",          # Critical: Never default to 5432 or 5000!
}

def _get_db_env(key):
    return _env(key, DB_DEFAULTS[key])

# Compose DB config dict, but DO NOT IMPORT OR CONNECT AT STARTUP (no socket, no psycopg, etc).
DATABASES = {}

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    # Parse from dj-database-url if and only if DATABASE_URL is present.
    # Import here, but parsing is guaranteed not to connect to the network or resolve hosts.
    import dj_database_url
    db_cfg = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    # Patch engine to prefer psycopg v3 if installed, else fallback to psycopg2.
    def _prefer_psycopg(db_cfg):
        if db_cfg.get("ENGINE", "").startswith("django.db.backends.postgresql"):
            # Only try import once and avoid shadowing
            try:
                import psycopg  # noqa: F401
            except ImportError:
                db_cfg["ENGINE"] = "django.db.backends.postgresql_psycopg2"
            else:
                db_cfg["ENGINE"] = "django.db.backends.postgresql"
        return db_cfg
    db_cfg = _prefer_psycopg(db_cfg)
    db_cfg.setdefault("NAME", DB_DEFAULTS["DB_NAME"])
    db_cfg.setdefault("USER", DB_DEFAULTS["DB_USER"])
    db_cfg.setdefault("PASSWORD", DB_DEFAULTS["DB_PASSWORD"])
    db_cfg.setdefault("HOST", DB_DEFAULTS["DB_HOST"])
    db_cfg.setdefault("PORT", DB_DEFAULTS["DB_PORT"])
    DATABASES['default'] = db_cfg
else:
    db_cfg = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _get_db_env('DB_NAME'),
        'USER': _get_db_env('DB_USER'),
        'PASSWORD': _get_db_env('DB_PASSWORD'),
        'HOST': _get_db_env('DB_HOST'),
        'PORT': _get_db_env('DB_PORT'),
    }
    def _prefer_psycopg_simple(db_cfg):
        try:
            import psycopg  # noqa: F401
        except ImportError:
            db_cfg['ENGINE'] = 'django.db.backends.postgresql_psycopg2'
        else:
            db_cfg['ENGINE'] = 'django.db.backends.postgresql'
        return db_cfg
    db_cfg = _prefer_psycopg_simple(db_cfg)
    DATABASES['default'] = db_cfg
# CRITICAL: DO NOT VALIDATE, RESOLVE, or CONNECT HERE (settings import time).
# Do not add socket.gethostbyname, connection tests, or anything except environment sniffing and parse logic.

# --- END DATABASE CONFIGURATION ---

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
X_FRAME_OPTIONS = 'ALLOWALL'
